### ISSUE TITLE
Context filetype detection not working

### ISSUE THREAD

**Issue by ianpurvis** [tyru/caw.vim#100]
Given a single-file vue component, like `test.vue`
When I comment code in the script or style portion of the file
I expect `//` comments but I get `<!-- -->` html comments.

**Comment by ianpurvis** [comment]
I found detection of https://github.com/Shougo/context_filetype.vim was broken, fixed in #99

**Comment by himat** [comment]
I'm confused, I don't see `vue` in `after/ftplugin/*` in this repo. 
And indeed when I try to comment an html line in a .vue file, it uses the wrong comments. The plugin uses `/* ... */` for all lines in a vue file for me.

Does this commenter actually support vue files, and if so, how do I enable that?

**Comment by ianpurvis** [comment]
@himat It works, but you'll need to install the `context_filetype` plugin @ https://github.com/Shougo/context_filetype.vim
