### ISSUE TITLE
toggle caw error

### ISSUE THREAD

**Issue by hamsterBiscuit** [tyru/caw.vim#158]
![image](https://user-images.githubusercontent.com/19209958/104082190-21644900-526f-11eb-90eb-0c5cfce0381d.png)
 i use neovim 5.0
input gcc error

**Comment by yongqi-zhang** [comment]
![image](https://user-images.githubusercontent.com/19209958/104104727-da189f80-52e4-11eb-9c95-3137c6035e2c.png)
change lua file `tstree` to `tstree[1]`
is work for me.
i m lua new coder.
if you see is right 
fix it please. thanks! @tyru

**Comment by yongqi-zhang** [comment]
cool
