### ISSUE TITLE
Operatorが欲しい

### ISSUE THREAD

**Issue by thinca** [tyru/caw.vim#20]
コメントアウトやコメントトグルする operator が欲しいです！

**Comment by tyru** [comment]
マージしたい。

- [caw.vim 用のオペレータマッピング](http://rhysd.hatenablog.com/entry/2013/08/25/035533) by @rhysd 
- [operator-exec_command で caw.vim の operator を定義する](http://d.hatena.ne.jp/osyo-manga/20140602/1401720298) @osyo-manga

**Comment by tyru** [comment]
と、思ったけど、そもそもcaw.vimのoperatorってどんな機能が欲しいんでしょう？ @thinca @osyo-manga 
単にヴィジュアル選択して`gcc`マッピングを実行するようなやつですか？

**Comment by thinca** [comment]
だいたいそんな感じですが、ビジュアル選択だと `.` リピートができないので、できるやつだと嬉しいです。

**Comment by toshi32tony3** [comment]
+1

> だいたいそんな感じですが、ビジュアル選択だと```.```リピートができないので、できるやつだと嬉しいです。

visual-repeatの適用範囲がイケてないのはその通りなのですが、リピート自体は可能なので、とりあえずrhysdさんの実装で取り込んでもらえると嬉しいと思いました。

**Comment by tyru** [comment]
PR! PR!

**Comment by tyru** [comment]
実装しました。 #50
