### ISSUE TITLE
haskellで動作しません

### ISSUE THREAD

**Issue by LCreator** [tyru/caw.vim#24]
caw.vim/autoload/caw.vim
368行目に以下の様にhaskellは'--'でコメントアウトする、と追加すると
haskellで動くようになりました。

autoload/caw.vim-    \   'h': '//',
autoload/caw.vim:    \   'haskell': '--',
autoload/caw.vim-    \   'haml': '-#',

**Comment by tyru** [comment]
対応しました。
報告ありがとうございます。
