### ISSUE TITLE
White space after uncomment.

### ISSUE THREAD

**Issue by blindFS** [tyru/caw.vim#25]
After uncommenting a block containing empty lines, white spaces will occur.

**Comment by tyru** [comment]
Please give me more details.

**Comment by tyru** [comment]
ping @blindFS 
(Will close this issue next weekend if you do not reply)

**Comment by tyru** [comment]
@blindFS I can't reproduce in `filetype=vim`.
What filetype did you use? (if you remember)

`gcc` or `gcui` on the following line will remove both a comment and a whitespace.

```viml
"[whitespace]
```

**Comment by tyru** [comment]
Sorry for delay to reply... ;(

**Comment by tyru** [comment]
> (Will close this issue next weekend if you do not reply)

closed.
