### ISSUE TITLE
Haskell should come After haml

### ISSUE THREAD

**Issue by lesguillemets** [tyru/caw.vim#27]
I just noticed a very tiny thing:  in [`autoload/caw.vim`](https://github.com/tyru/caw.vim/blob/master/autoload/caw.vim#L368), there is

````
    \   'haskell': '--',
    \   'haml': '-#',
````

but ha-M lies before ha-S, so the proper order is `haml` then `haskell`.

**Comment by tyru** [comment]
Thanks!
