### ISSUE TITLE
バッファを閉じた(:q)ときに E108

### ISSUE THREAD

**Issue by machakann** [tyru/caw.vim#46]
すいません、確かな再現方法がいまいちわかっていないのですが、最近からバッファを閉じたときに次のようなエラーがでる時があります。

> function \<SNR>23_LoadFTPlugin の処理中にエラーが検出されました:
> 行    2:
> E108: その変数はありません: "b:caw_wrap_oneline_comment"

`<SNR>23` が指すのは `$VIMRUNTIME/ftplugin.vim` で、 `s:LoadFTPlugin()` の冒頭は
```vim
  func! s:LoadFTPlugin()
    if exists("b:undo_ftplugin")
      exe b:undo_ftplugin
      unlet! b:undo_ftplugin b:did_ftplugin
    endif
```
なので、 `b:undo_ftplugin` の内容に関係しそうです。help を引いてそのウィンドウを閉じたときに多いような気がします。

**Comment by tyru** [comment]
@machakann dein.vim 使ってますか？であればおそらく dein 側の問題です。
http://lingr.com/room/vim/archives/2016/03/22#message-23152069

**Comment by tyru** [comment]
dein 側の問題であることを確認したら閉じます。

**Comment by machakann** [comment]
dein.vim は使っていません、neobundle.vim を使っています。こちらも同様でしょうか？

**Comment by tyru** [comment]
neobundle ユーザからの報告は初めてですが、おそらく同じ問題が起きます。
https://github.com/Shougo/neobundle.vim/blob/d4e76e8230f73949534920c52b4b9d85763ba11f/autoload/neobundle/config.vim#L731-L732

**Comment by machakann** [comment]
ありがとうございます。該当行が `:set filetype=xxx` 相当になって同様のオートコマンドイベントが登録されているということでしょうか。たしかに、それかもしれません。閉じるタイミングはお任せします。

**Comment by machakann** [comment]
すいません、ヘルプの件は関係ないことに気が付きました。どうもマークダウンを編集中に再現します。オートコマンドも関係ないですね。

起きる場合は `b:undo_ftplugin` の内容が
```
setlocal commentstring< matchpairs< omn..< comments< formatoptions< | unlet! b:match_ignorecase b:match_skip b:match_wo..:browsefilter | unlet b:caw_wrap_oneline_comment|setl cms< com< fo< flp< | unlet b:caw_wrap_oneline_comment
```
のように `unlet b:caw_wrap_oneline_comment` が重複していました。ファイルタイププラグインが再読み込みされるのはあり得ることのように思えるので、`:help write-filetype-plugin` にあるように重複を防止するのはいかがでしょうか？
```vim
	if exists("b:did_ftplugin")
	  finish
	endif
	let b:did_ftplugin = 1
```
`b:did_ftplugin` ではなく独自の名前にする必要はあるかもしれませんが。何か勘違いがあるかもしれませんので、その場合は教えてください。

**Comment by machakann** [comment]
再現方法が分かりました。プラグインマネージャの問題でもないように思います。

1. 適当なマークダウンファイル `foo.md` を作る (`touch foo.md`)
2. `vim -u NONE -N`
3. `:filetype plugin on`
4. `:set rtp+=/path/to/caw.vim,/path/to/caw.vim/after`
5. `:edit foo.md`
6. `:edit`

6 でバッファを開きなおすとタイトルのエラーが出ます。 

5 を `:15verbose edit foo.md` に置き換えて出力を眺めていたところ、マークダウンのファイルタイププラグインが html のファイルタイププラグインを読み込むために問題が起こっていることに気が付きました。このために `after/html/caw.vim` と `after/markdown/caw.vim` が読み込まれています。

`after/markdown/caw.vim` が後に読み込まれるので単純に `b:did_ftplugin` のような仕組みでも問題が出るようです。すいません、上で適当なことを言いました。
```vim
let b:caw_wrap_oneline_comment = ['something', 'something']
```
の後に `finish` するか、`b:undo_ftplugin` に重複が出ないような仕組みが必要そうです。

**Comment by tyru** [comment]
ありがとうございます。[Lingr でも同様の指摘を受けました](http://lingr.com/room/vim/archives/2016/03/22#message-23153183)。
caw.vim 側で修正します。

**Comment by tyru** [comment]
@machakann #47 でPRを出しました。`fix/dup-entries-undo_ftplugin`ブランチに切り替えて試して頂けますか？

**Comment by machakann** [comment]
エラーが出なくなるのを確認しました。

ただ、これだと `after/html/caw.vim` が `b:caw_wrap_oneline_comment` を先に設定して `after/markdown/caw.vim` が読み込まれるのをブロックするので、マークダウンの場合はいいですが他の場合で問題が出そうな気がします。 `b:caw_wrap_oneline_comment` などはあとに読み込まれるものに上書かれたほうが良いのではないでしょうか？

**Comment by tyru** [comment]
なるほど。ありがとうございます。修正します。

**Comment by tyru** [comment]
@machakann 修正しました。

**Comment by tyru** [comment]
master にもマージしてあります。

**Comment by machakann** [comment]
ありがとうございました！
