### ISSUE TITLE
`<Plug>(caw:zeropos:toggle)` does not work on a buffer of ft=vim

### ISSUE THREAD

**Issue by ichitera** [tyru/caw.vim#88]
## Issue
When `<Plug>(caw:zeropos:toggle)` was executed on a buffer of ft=vim, vim showed the following error.
```
[Vim(let):E704: Funcref variable name must start with a capital: caw_zeropos_sp]:
:[function caw#keymapping_stub[48]..15[7]..11[3]..6, line 3]
```
![error gif](https://user-images.githubusercontent.com/31098747/45914030-efe6ca00-be79-11e8-850f-a0d5936f3401.gif)

## The way to reproduce
1. execute `vim -u vimrc -N` (the `vimrc` is attached below)
2. execute `:e some_vim_file.vim`
3. insert some text
4. type `gcc` in a line
5. you will see the error

The vimrc used in the above steps is the following:
```viml
language C
set runtimepath+=~/.vim/bundle/vim-operator-user/
set runtimepath+=~/.vim/bundle/caw.vim/
set runtimepath+=~/.vim/bundle/caw.vim/after/
filetype plugin indent on

let g:caw_operator_keymappings = 1
nmap gcc <Plug>(caw:zeropos:toggle)
```

## Note
The error causes after dedb0635cd3f5753b924be9359ceb19d1ed9e9e5

## Environment
- OS: Windows 10 64bit
- vim: 8.425
- kana/vim-operator-user:  kana/vim-operator-user@c3dfd41c1ed516b4b901c97562e644de62c367aa
- tyru/caw.vim: tyru/caw.vim@2427ba1379b1bb3c7b737921219a346f10a21ad8

**Comment by tyru** [comment]
Thanks!
